### ISSUE TITLE
Dart networks tables Pub Package

### ISSUE THREAD

**Issue by itamarsch** [3015RangerRobotics/2023Public#1]
I think all Frc teams that would like to create a flutter dashboard would benefit alot from your implementation of the NTv4 protocol.
And seeing as you have already uploaded the implementations to github creating a package would make the process of using the package alot easier.

**Comment by mjansen4857** [comment]
Working on some PathPlanner reworks at the moment and I think I want to use NT4 for some stuff so I'll use that as an opportunity to make it a package when I get around to that part. Might change quite a bit compared to how it currently works. I don't think its that user friendly at the moment.

**Comment by mjansen4857** [comment]
Published: https://pub.dev/packages/nt4

Current version is basically the same as in this repo, will probably update it over time. Feel free to contribute if interested.
